241012 백준 10431 java
SeungAh-Yoo99/Hell-of-Algorithms pull request #230
Opened 2024-10-15 02:06 UTC by rlfrkdms1

## 241012
close #221 

### 문제집 : [IT기업 및 대기업 계열사 코테보면서 비슷했던 문제들](https://www.acmicpc.net/workbook/view/8708)

- 10431
   - LinkedList
   - 구현

### ETC

2024-10-17 12:30 UTC, SeungAh-Yoo99 requested changes

2024-10-17 12:30 UTC, SeungAh-Yoo99 commented on 길가은/BOJ/B10431.java
알고리즘 연습 겸 이분 탐색으로 풀어봅시다~
가은님은 **특별히** 이분 탐색으로 풀기 전까지 머지 못해용~~
**`binarySearch()` 메소드 사용 금지**

2024-10-17 12:30 UTC, SeungAh-Yoo99 commented on 길가은/BOJ/B10431.java
> +        }
여러 줄 출력할 땐, `StringBuilder` 사용하는게 시간 단축 많이 돼욥
다른 분들은 `BufferedWriter`도 많이 사용하시는 거 같은데, 찾아보고 더 효율 좋아보이는 거 사용하시면 될 듯!!

프로그래머스에서는 답 출력 안하고 리턴만 하면 돼서 출력 신경써줄 필요 없지만,
가끔 자기네 회사 자체 툴 써서 코테 보는 곳이 있어요.
그런 곳에서 백준처럼 출력하라고 나오는 곳들이 있는데, 확률은 적지만 혹시 모를 상황에 대비해서 출력도 신경써봅시다~
그리고 백준에서도 출력 신경 안쓰면 시간초과 나오는 문제 간혹 있음!!

2024-10-17 12:33 UTC, rlfrkdms1 commented on 길가은/BOJ/B10431.java
엇 넵 이분탐색 공부해보겠습니다 !

2024-10-17 12:33 UTC, rlfrkdms1 commented on 길가은/BOJ/B10431.java
> +        }
넵 감사합니다 ㅎㅎ 귀찮아서 그냥 썼는데 딱 걸렸네요 ㅎㅎ

2024-11-03 16:46 UTC, SeungAh-Yoo99 approved these changes

2024-11-03 16:47 UTC, merged